name: Checkout and Install

inputs:
  apt:
    description: 'Install APT packages'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.8

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - shell: bash
      run: corepack enable

    - shell: bash
      run: pnpm --version

    - name: Install system (Playwright requirements)
      shell: bash
      if: ${{ inputs.apt }}
      run: |
        sudo apt-get update
        pnpm exec playwright install-deps
        pnpm exec playwright install

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
        cache-dependency-path: "**/pnpm-lock.yaml"

    - name: Install dependencies
      shell: bash
      run: pnpm i