name: Deploy Repo X
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: 'No source specified'
  push:
    paths:
      - 'release-versions/*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # @T00D00 - "pnpm run build" fails with symlinks
      - name: Clone sub-docs
        run: |
          git clone git@github.com/shopware/frontends.git docs/frontends
          git clone git@github.com/shopware/admin-extension-sdk.git docs/resources/admin-extension-sdk
          git clone git@github.com/shopware/store-api-reference.git docs/resources/store-api-reference
          git clone git@github.com/shopware/admin-api-reference.git docs/resources/admin-api-reference
          git clone git@github.com/shopware/meteor-icon-kit.git docs/resources/meteor-icon-kit

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push

      - name: Build project
        run:

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"