name: Notify downstream
on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream workflow
        run: |
          JSON_STRING=$( jq -n \
                  --arg ref "$GITHUB_REF" \
                  --arg repository "$GITHUB_REPOSITORY" \
                  '{ref: $ref, repository: $repository}' )
          
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/shopware/developer-documentation-vitepress/actions/workflows/deploy.yml/dispatches \
          -d $JSON_STRING

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: shopware/developer-documentation-vitepress
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'