redirects:
    developers-guide/plugin-guidelines/: https://developers.shopware.com/developers-guide/plugin-guidelines/
    guides/integrations-api/store-api-guide: guides/integrations-api/README.md
    guides/integrations-api/store-api-guide/register-a-customer: guides/integrations-api/README.md
    guides/integrations-api/store-api-guide/search-for-products: guides/integrations-api/README.md
    guides/integrations-api/store-api-guide/work-with-the-cart: guides/integrations-api/README.md
    guides/integrations-api/store-api-guide/handling-the-payment: guides/integrations-api/README.md
    guides/integrations-api/store-api-guide/faq: guides/integrations-api/README.md
    guides/integrations-api/admin-api/: guides/integrations-api/README.md
    guides/integrations-api/admin-api/action-routes: guides/integrations-api/README.md
    guides/integrations-api/admin-api/authentication: guides/integrations-api/README.md
    guides/integrations-api/admin-api/reading-entities: guides/integrations-api/README.md
    guides/integrations-api/admin-api/writing-entities/: guides/integrations-api/README.md
    guides/integrations-api/admin-api/writing-entities/associations: guides/integrations-api/README.md
    guides/integrations-api/admin-api/writing-entities/bulk-payloads: guides/integrations-api/README.md
    guides/integrations-api/admin-api/writing-entities/product-data: guides/integrations-api/README.md
    resources/references/api-reference/admin-api-reference: guides/integrations-api/README.md
    concepts/extensions/elasticsearch-concept: concepts/framework/elasticsearch.md
